### ISSUE TITLE
Crash occuring randomly? - 1.20.1 Forge

### ISSUE THREAD

**Issue by DavidFlisar** [P3pp3rF1y/SophisticatedCore#241]
I am not quite sure how to recreate this crash, but I can provide information that each of the 2 players in the game have a Copper backpack on. Is it maybe interfering with Inventory Profiles Next, which has sorting for chests?

Anyways here is the log:"

[01:51:58] [Render thread/INFO]: Minimap session finalized.
[01:51:58] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[01:51:58] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[01:51:58] [Render thread/INFO]: Stopping JEI
[01:51:58] [Render thread/INFO]: Sending Runtime Unavailable...
[01:51:58] [Render thread/INFO]: Stopping JEI GUI
[01:51:58] [Render thread/INFO]: Sending Runtime Unavailable took 1.355 ms
[01:51:58] [Render thread/INFO]: Curios disabled
[01:51:58] [Render thread/INFO]: Stopping worker threads
[01:51:58] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[01:52:00] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:123) ~[CorgiLib-forge-1.20.1-4.0.1.1.jar%23363!/:4.0.1.1]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.32.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.32.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.32.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.32.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 74 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handler$cek003$smoothswapping$onInit(ServerboundContainerClickPacket.java:558) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.<init>(ServerboundContainerClickPacket.java:30) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.handleInventoryMouseClick(StorageScreenBase.java:813) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23464!/:1.20.1-0.6.22.611]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_6597_(StorageScreenBase.java:760) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23464!/:1.20.1-0.6.22.611]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_6375_(StorageScreenBase.java:828) ~[sophisticatedcore-1.20.1-0.6.22.611.jar%23464!/:1.20.1-0.6.22.611]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23492!/:?]
	... 30 more
[01:52:00] [Netty Server IO ICE #9/ERROR]: Network Exception Caught

"
When analyzing the issue with ChatGPT, it seems to come up with this reason:"java.lang.IndexOutOfBoundsException: Index 74 out of bounds for length 46" and says that it is trying to access index 74, while there are only 46 slots. I had this crash happen 2 times in a timespan of 3 hours of playtime.

**Comment by P3pp3rF1y** [comment]
There is an easy fix for this - just remove smooth swapping mod. They have a bug in their code for a really long time now that is breaking sophisticated gui interactions.

**Comment by DavidFlisar** [comment]
Thank god man. At least there isn't a big mod breaking Sophisticated mods, because this mod is sick. I have to ask, how did you know that Smooth Swapping mod was affecting it?

But yea as for now I will be removing the swapping mod until there comes an alternative.

**Comment by P3pp3rF1y** [comment]
Easy - this issue has been happening for a long time now and was reported tens of times so now when someone reports bug and there's IndexOutOfBounds exception in it the first thing I check for is whether they have smooth swapping in the pack
