### ISSUE TITLE
Crash when using lava bucket in auto smelting upgrade

### ISSUE THREAD

**Issue by TheAwiteb** [P3pp3rF1y/SophisticatedCore#256]
Hi, when I tried to smelt my ores with a lava bucket using the auto smelting upgrade, the game crashed. I think this is because the auto smelting upgrade is trying to stack the lava bucket when it can't be stacked. I'm using version 0.6.31, the latest version

<details>
<summary>Minecraft Crash Report</summary>

```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-09-03 19:32:22
Description: Ticking block entity

java.lang.RuntimeException: Invalid stack 1 minecraft:bucket for slot 1)
	at TRANSFORMER/neoforge@21.1.31/net.neoforged.neoforge.items.ComponentItemHandler.setStackInSlot(ComponentItemHandler.java:65) ~[neoforge-21.1.31-universal.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/sophisticatedcore@0.6.31/net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.CookingLogic.setFuel(CookingLogic.java:274) ~[sophisticatedcore-1.21-0.6.31.631.jar%23191!/:1.21-0.6.31.631] {re:classloading}
	at TRANSFORMER/sophisticatedcore@0.6.31/net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.CookingLogic.updateFuel(CookingLogic.java:219) ~[sophisticatedcore-1.21-0.6.31.631.jar%23191!/:1.21-0.6.31.631] {re:classloading}
	at TRANSFORMER/sophisticatedcore@0.6.31/net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.CookingLogic.lambda$tick$2(CookingLogic.java:73) ~[sophisticatedcore-1.21-0.6.31.631.jar%23191!/:1.21-0.6.31.631] {re:classloading}
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at TRANSFORMER/sophisticatedcore@0.6.31/net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.CookingLogic.tick(CookingLogic.java:72) ~[sophisticatedcore-1.21-0.6.31.631.jar%23191!/:1.21-0.6.31.631] {re:classloading}
	at TRANSFORMER/sophisticatedcore@0.6.31/net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.AutoCookingUpgradeWrapper.tick(AutoCookingUpgradeWrapper.java:107) ~[sophisticatedcore-1.21-0.6.31.631.jar%23191!/:1.21-0.6.31.631] {re:classloading}
	at TRANSFORMER/sophisticatedstorage@0.10.26/net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity.lambda$serverTick$4(StorageBlockEntity.java:328) ~[sophisticatedstorage-1.21-0.10.26.816.jar%23192!/:1.21-0.10.26.816] {re:classloading}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {re:mixin}
	at TRANSFORMER/sophisticatedstorage@0.10.26/net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity.serverTick(StorageBlockEntity.java:328) ~[sophisticatedstorage-1.21-0.10.26.816.jar%23192!/:1.21-0.10.26.816] {re:classloading}
	at TRANSFORMER/sophisticatedstorage@0.10.26/net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockBase.lambda$getTicker$5(StorageBlockBase.java:114) ~[sophisticatedstorage-1.21-0.10.26.816.jar%23192!/:1.21-0.10.26.816] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:706) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:783) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:428) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23181!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

</details>

**Comment by P3pp3rF1y** [comment]
This was solved in a release a while back so closing.
