### ISSUE TITLE
[Bug] Server crash InventoryHandler.getSlotStack ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Ricket** [P3pp3rF1y/SophisticatedCore#341]
Apparently, a creeper exploded and burst open a gold chest, and then both client & server crashed.

`sophisticatedcore-1.20.1-0.7.2.756` in pack All the Mods 9 (ATM9) version 0.3.5.

```
java.lang.ArrayIndexOutOfBoundsException: Index 119 out of bounds for length 81
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?] {}
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.getSlotStack(InventoryHandler.java:264) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.updateSlotNbt(InventoryHandler.java:107) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.onContentsChanged(InventoryHandler.java:92) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageInventorySlot.m_6654_(StorageInventorySlot.java:25) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.triggerSlotListeners(StorageContainerMenuBase.java:806) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.broadcastChangesIn(StorageContainerMenuBase.java:1457) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.m_38946_(StorageContainerMenuBase.java:1431) ~[sophisticatedcore-1.20.1-0.7.2.756.jar%23856!/:1.20.1-0.7.2.756] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:435) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:ldlib-common.mixins.json:accessor.ServerPlayerAccessor,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:logprot.mixins.json:ServerPlayerMixin,pl:mixin:APP:alltheleaks.mixins.json:main.ServerPlayerMixin,pl:mixin:APP:adastra-common.mixins.json:common.radio.ServerPlayerMixin,pl:mixin:APP:glitchcore.forge.mixins.json:MixinServerPlayer,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:8669) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.redirect$cjj000$observable$onTickNonPassenger(ServerLevel.java:8685) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:adastra.mixins.json:common.multipart.LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,re:classloading,pl:mixin:APP:alltheleaks.mixins.json:main.EntityTickListMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23927!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```
[crash-2024-12-19_00.29.23-server.txt](https://github.com/user-attachments/files/18193843/crash-2024-12-19_00.29.23-server.txt)

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of core
